experiments:
  user_home_feed: # Home feed collection for logged in user
    variants:
      - base
      - more_random
      - top_past_week_random
      - newer
    weights:
      - 25
      - 25
      - 25
      - 25
    goals:
      - makes_comment
      - makes_reaction
      - makes_article_pageview_four_days_in_week
exclude:
  bots: true

# Dashboard performance
cache: true

# For logged-in users we'll explicitely pass participant. 
# If we experiment on non-logged in, we don't want to collect cookies anyway.
cookies: false